name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          --network host

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/habit-tracker-backend .

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/habit-tracker-frontend .

      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/habit-tracker-backend

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/habit-tracker-frontend